WORLD_NEWS_CHANNELS = [
    # Wire Services
    {"id": "UChqUTb7kYRX8-EiaN3XFrSQ", "name": "Reuters"},
    {"id": "UC52X5wxOL_s5yw0dQk7NtgA", "name": "Associated Press"},
    {"id": "UC86dbj-lbDks_hZ5gRKL49Q", "name": "AFP News Agency"},
    # Global Broadcasters
    {"id": "UC16niRr50-MSBwiO3YDb3RA", "name": "BBC News"},
    {"id": "UCNye-wNBqNL5ZzHSJj3l8Bg", "name": "Al Jazeera English"},
    {"id": "UCQfwfsi5VrQ8yKZ-UWmAEFg", "name": "France 24 English"},
    {"id": "UCknLrEdhRCp1aegoMqRaCZg", "name": "DW News"},
    {"id": "UCSrZ3UV4jOidv8ppoVuvW9Q", "name": "Euronews English"},
    {"id": "UC7fWeaHhqgM4Ry-RMpM2YYw", "name": "TRT World"},
    {"id": "UCoMdktPbSTixAyNGwb-UYkQ", "name": "Sky News"},
    {"id": "UCTrQ7HXWRRxr7OsOtodr2_w", "name": "Channel 4 News"},
    # USA
    {"id": "UCBi2mrWuNuyYy4gbM6fU18Q", "name": "ABC News"},
    {"id": "UC8p1vwvWtl6T73JiExfWs1g", "name": "CBS News"},
    {"id": "UCIALMKvObZNtJ6AmdCLP7Lg", "name": "Bloomberg TV"},
    {"id": "UC6ZFN9Tx6xh-skXCuRHCDpQ", "name": "PBS NewsHour"},
    # Asia-Pacific
    {"id": "UC83jt4dlz1Gjl58fzQrrKZg", "name": "CNA"},
    {"id": "UCSPEjw8F2nQDtmUKPFNF7_A", "name": "NHK World"},
    {"id": "UCzznO4xSV8BKnUBPyswtCUw", "name": "ARIRANG News"},
    {"id": "UCVgO39Bk5sMo66-6o6Spn6Q", "name": "ABC News Australia"},
    {"id": "UCO0akufu9MOzyz3nvGIXAAw", "name": "Sky News Australia"},
    # Middle East
    {"id": "UCvHDpsWKADrDia0c99X37vg", "name": "i24 News"},
    {"id": "UCI8DegIWgK51cGakXcf1dOQ", "name": "Arab News"},
    # Africa
    {"id": "UCEXGDNclvmg6RW0vipJYsTQ", "name": "Channels TV"},
    {"id": "UCgp4A6I8LCWrhUzn-5SbKvA", "name": "TVC News Nigeria"},
    {"id": "UCKVsdeoHExltrWMuK0hOWmg", "name": "KTN News Kenya"},
    {"id": "UCqBJ47FjJcl61fmSbcadAVg", "name": "NTV Kenya"},
    {"id": "UC8yH-uI81UUtEMDsowQyx1g", "name": "SABC News"},
    # Newspapers
    {"id": "UCqnbDFdCpuN8CMEg0VuEBqA", "name": "New York Times"},
    {"id": "UCHd62-u_v4DvJ8TCFtpi4GA", "name": "Washington Post"},
    {"id": "UCK7tptUDHh-RYDsdxO1-5QQ", "name": "Wall Street Journal"},
    {"id": "UCHpw8xwDNhU9gdohEcJu4aA", "name": "The Guardian"},
    {"id": "UCoUxsWakJucWg46KW5RsvPw", "name": "Financial Times"},
    {"id": "UCshwRhftzkiov5wKR7M_LsQ", "name": "The Independent"},
    {"id": "UC0p5jTq6Xx_DosDFxVXnWaQ", "name": "The Economist"},
    {"id": "UC4p_I9eiRewn2KoU-nawrDg", "name": "Straits Times"},
    {"id": "UC4SUWizzKc1tptprBkWjX2Q", "name": "South China Morning Post"},
    # South Asia
    {"id": "UCuOtdpOPjHeoEAT4i44mVOg", "name": "Ada Derana English"},
]

NATIONAL_ENGLISH_CHANNELS = [
    {"id": "UCef1-8eOpJgud7szVPlZQAQ", "name": "CNN-News18"},
    {"id": "UCwqusr8YDwM-3mEYTDeJHzw", "name": "Republic World"},
    {"id": "UCckHqySbfy5FcPP6MD_S-Yg", "name": "Times of India"},
    {"id": "UC6RJ7-PaXg6TIH2BzZfTV7w", "name": "Times Now"},
    {"id": "UCtFQDgA8J8_iiwc5-KoAQlg", "name": "ANI News"},
    {"id": "UCz8QaiQxApLq8sLNcszYyJw", "name": "Firstpost"},
    {"id": "UCYPvAwZP8pZhSMW8qs7cVCw", "name": "India Today"},
    {"id": "UCm7lHFkt2yB_WzL67aruVBQ", "name": "HT Videos"},
    {"id": "UCZFMm1mMw0F81Z37aaEzTUA", "name": "NDTV"},
    {"id": "UC_gUM8rL-Lrg6O3adPW9K1g", "name": "WION"},
    {"id": "UCc8J8UvzwMZHnO0MX1NTmSw", "name": "The Tribune"},
    {"id": "UCytSP0M0Jdnw6qIy3Y-nTig", "name": "NewsX"},
    {"id": "UCUI9vm69ZbAqRK3q3vKLWCQ", "name": "Mint"},
    {"id": "UCJEDFSxHHOW1PpBccdSxOTA", "name": "Indian Express"},
    {"id": "UCqTa3sNT6SfiQ2DQK_kuWlA", "name": "Oneindia"},
    {"id": "UCuyRsHZILrU7ZDIAbGASHdA", "name": "The Print"},
    {"id": "UCWCEYVwSqr7Epo6sSCfUgiw", "name": "Mirror Now"},
    {"id": "UCLIMdoS-InL1-GIBUKSvydg", "name": "Mid-Day"},
    {"id": "UC3njZ48-FDxLleBYaP0SZIg", "name": "The Hindu"},
    {"id": "UCQtVJ-76KjPds9evTODkq-A", "name": "New Indian Express"},
    {"id": "UCHDXXHPrz-1GVbK_qk82hBQ", "name": "Deccan Herald"},
    {"id": "UCw8Fc5R0Q5yyS3KrDCPM3xg", "name": "Times Now World"},
    {"id": "UCRK4FDIkUyslEAUdyRDdCtQ", "name": "News9 Live"},
    {"id": "UCJFOER35ggIWwsXh2ZDnqyg", "name": "The Economic Times"},
]

NATIONAL_HINDI_CHANNELS = [
    {"id": "UCt4t-jeY85JegMlZ-E5UWtA", "name": "Aaj Tak"},
    {"id": "UCx8Z14PpntdaxCt2hakbQLQ", "name": "The Lallantop"},
    {"id": "UCttspZesZIDEwwpVIgoZtWQ", "name": "India TV"},
    {"id": "UCRWFSbif-RFENbBrSiez1DA", "name": "ABP News"},
    {"id": "UCPP3etACgdUWvizcES1dJ8Q", "name": "News18 India"},
    {"id": "UC9CYT9gSNLevX5ey2_6CK0Q", "name": "NDTV India"},
    {"id": "UCOutOIcn_oho8pyVN3Ng-Pg", "name": "TV9 Bharatvarsh"},
    {"id": "UCMk9Tdc-d1BIcAFaSppiVkw", "name": "Times Now Navbharat"},
    {"id": "UC531MlZA5LUbeGwEN_zcppw", "name": "News18 Bihar Jharkhand"},
    {"id": "UC7wXt18f2iA3EDXeqAVuKng", "name": "Republic Bharat"},
    {"id": "UCIvaYmXn910QMdemBG3v1pQ", "name": "Zee News"},
    {"id": "UCKwucPzHZ7zCUIf7If-Wo1g", "name": "DD News"},
    {"id": "UC8eEZ-l5z_zzG8GT0Tu0PaA", "name": "India Dot Com"},
    {"id": "UCP_wvXToU5ohFLbTAkatvsw", "name": "Amar Ujala"},
    {"id": "UCCJRFl1Qjo83GG_09U-DIBA", "name": "Hindustan"},
    {"id": "UCvxi7_X1VSaMr_osIamYNaw", "name": "NMF News"},
    {"id": "UCOjgc1p2hJ4GZi6pQQoXWYQ", "name": "Oneindia Hindi"},
    {"id": "UCsNdeLwEZf86swPD3qJJ7Dw", "name": "News Nation"},
    {"id": "UCUGwnDFBHY52YhgVjn-Tvww", "name": "ABP Ganga"},
    {"id": "UCSKgOW8Pg_eZymYJyJc432g", "name": "Dainik Jagran"},
    {"id": "UCafYgzpyw7aIUYOLjjADu7w", "name": "News18 UP Uttarakhand"},
    {"id": "UCBwc2cbPpvxNCNEI2-8YrqQ", "name": "News18 MP Chhattisgarh"},
    {"id": "UCl8wUKzoUVzg7U6ky1ZR8hQ", "name": "Navbharat Times"},
    {"id": "UC_cZYFovNQTsKw1ZLmO_AMA", "name": "First India News"},
    {"id": "UClmlqOOktUTpfW0EkTiqSjQ", "name": "Aaj Tak HD"},
    {"id": "UCmphdqZNmqL72WJ2uyiNw5w", "name": "ABP Live"},
]

BENGALI_CHANNELS = [
    {"id": "UCv3rFzn-GHGtqzXiaq3sWNg", "name": "ABP Ananda"},
    {"id": "UCdF5Q5QVbYstYrTfpgUl0ZA", "name": "Zee 24 Ghanta"},
    {"id": "UCHCR4UFsGwd_VcDa0-a4haw",  "name": "TV9 Bangla"},
    {"id": "UCbf0XHULBkTfv2hBjaaDw9Q",  "name": "News18 Bangla"},
    {"id": "UCajVjEHDoVn_AHsunUZz_EQ",  "name": "Republic Bangla"},
    {"id": "UCdfOu3dJAYCc99mUy8hyfMw",  "name": "Aaj Tak Bangla"},
    {"id": "UCJ3I6MHOz5exARlTW_meOGQ",  "name": "Calcutta News"},
    {"id": "UC7GSS1hr39KcjdsKqAO76aQ",  "name": "Asianet News Bangla"},
    {"id": "UCHHYiu-zVZ307SN_gNqr88Q",  "name": "Tribe TV"},
    {"id": "UCe4GErYKwpMUJWZpxOiATYA",  "name": "DD Bangla News"},
    {"id": "UCycQauzU5n3DwQdgk3cw91A",  "name": "R Plus News 24x7"},
    {"id": "UC-drIvdQ0sZlyPXCizj4vgQ",  "name": "News Time Bangla"},
    {"id": "UC75RbtivNkL0XLElFAxg_zA",  "name": "High News"},
    {"id": "UCESY9RzEDPsb9lRLMxAirwQ",  "name": "Anandabazar Patrika"},
    {"id": "UCWoPoR2Jho2tbFV4TttLNdA",  "name": "Bartaman"},
    {"id": "UCPYZ_TMaFSsAGyedFpwyufA",  "name": "Ei Samay"},
    {"id": "UCkwTQGJelg1F-gV2ZmfPg8Q",  "name": "Aajkaal"},
    {"id": "UCLPCvTftdZpZQSM-mckfqXQ",  "name": "Sangbad Pratidin"},
    {"id": "UCdx_kjAFLinvdnEkdklgoNQ",  "name": "Ganashakti"},
    {"id": "UCXDw7ADM9CnoGPEk3aSsHaQ",  "name": "Uttar Banga Sambad"},
    {"id": "UCpthbAb5DDRfcG68VMn6q0g",  "name": "Indian Express Bangla"},
]

HINDI_RIGHT_OPINION_CHANNELS = [
    {"id": "UCloWBBZ3E9b9NGW3r30DN5A", "name": "AKTK"},
    {"id": "UCsDTy8jvHcwMvSZf_JGi-FA", "name": "Abhi and Niyu"},
    {"id": "UC2bBsPXFWZWiBmkRiNlz8vg", "name": "Abhijit Chavda"},
    {"id": "UCsu4YmPw7E9PyGrWQG6fT9g", "name": "Advaita Kala Now"},
    {"id": "UC0PV5M3VlgXlP0wUqTJIIeQ", "name": "Ajeet Bharti"},
    {"id": "UCgX-nwxANLWE1d087jWlKQQ", "name": "Amber Zaidi Official"},
    {"id": "UCPJ_UzD4PEC-_vwN32amlIQ", "name": "Open Letter"},
    {"id": "UCNd46hD9lsr9NDliR--u4KQ", "name": "Anju Pankaj"},
    {"id": "UCp-1mZlbdVhj0j49m4bPspA", "name": "Anuj Awasthi"},
    {"id": "UC_gVr8TXCS0METhTLsps-sA", "name": "Apka Akhbar"},
    {"id": "UCD5W5_9TVSsIgYIkt47sWgw", "name": "Ashwini Upadhyay"},
    {"id": "UCfBfBd-1kvCOPxVll8tBJ9Q", "name": "Bharat Vaarta"},
    {"id": "UCnx0p9wzQXoBXOCRIeUfUrg", "name": "Budhi Media"},
    {"id": "UCGaOkbpMXx4j07kxQYpxFDA", "name": "Capital TV India"},
    {"id": "UCu3ix1BLMKTIIcjjXo-4X3w", "name": "Centre for Indic Studies"},
    {"id": "UC4vgB_qDWH3-RrgHE1isOYQ", "name": "DK Dubey"},
    {"id": "UCVVRDJbTe6q6FJRR4m3h3_A", "name": "DEF Talks by Aadi"},
    {"id": "UC4Yk3q9vmANVVMXOST89kxQ", "name": "Defensive Offence"},
    {"id": "UCwmgD2dyF1cJEFoQhjMrGrA", "name": "Do News Today"},
    {"id": "UCQlshr3xpvpcCeAZvGRz9Zg", "name": "Engineer Reveals"},
    {"id": "UCYldxBSTvUwJiw3haNlbccw", "name": "Rizwan Ahmed Adv"},
    {"id": "UC_hqg81N9k0R6xna0aNGoPw", "name": "Gunners Shot"},
    {"id": "UCVlWRiW6C6WVgOnHv4xSUjw", "name": "Harish Burnwal"},
    {"id": "UC0BQdLALVmrUeX5wvsEOEdA", "name": "Media Harsh VT"},
    {"id": "UCNViMnyO8ZaPyrGQfSn8xAA", "name": "HDV News Official"},
    {"id": "UCpelPgePHrkrFYGgtFD8xsQ", "name": "India In Details"},
    {"id": "UCE_F0nmdE-4puiTvzVh10bg", "name": "India This Week by Amana Khalid"},
    {"id": "UCk85J3pqkn1y--k2wNMbthA", "name": "Rajiv Malhotra Official"},
    {"id": "UCnZhp2ugahf_NZN-RuT09HQ", "name": "Ishkaran Singh Bhandari"},
    {"id": "UCK-HHyVCfKYzhxVOJgBt73w", "name": "Keerthika Govindhasamy"},
    {"id": "UCmkmN_OMZP8pXmjvN8fNY7w", "name": "Key Fact"},
    {"id": "UCln9HY5pf2oXm0x2GwUfrHQ", "name": "Mahamtb"},
    {"id": "UCdnFIeHJGhSjRoLvTZpYldw", "name": "Neeraj Atri"},
    {"id": "UCVErsRbJ_QXpGoro5ri0Lww", "name": "Nitin Shukla Live"},
    {"id": "UCr6z9q34HbkngcjkhWV1_lA", "name": "Omkar Chaudhary Show"},
    {"id": "UCWt3UbeNDgNd97-VREMtS4g", "name": "OpIndia"},
    {"id": "UCt-ybO9Kw9QqG9Ts_YaPJgA", "name": "Spy Games Pavneet"},
    {"id": "UC5oAOrsfqTxLOmFNuK_S8ug", "name": "PGurus1"},
    {"id": "UCK3NMOnCHSm87Ga7ktoEyUA", "name": "PGurus"},
    {"id": "UCD72C2pY5ua8zOnnk5YAEqw", "name": "Praarabdh"},
    {"id": "UCefJQ7fUmr_gm6OKfAjRDIQ", "name": "Prachyam"},
    {"id": "UC1hHsI_EVwDxBTS0UajEPQA", "name": "Public 24x7"},
    {"id": "UCoDiyU0xjSXJhmKJCqLeCNQ", "name": "Pyara Hindustan"},
    {"id": "UCNthz4aHxOekgLKDDERQbAA", "name": "Samrat Bhai"},
    {"id": "UC3nhAUpe7aBm1rFCBgoWWcA", "name": "Sangam Talks"},
    {"id": "UCAAkERuVmC4ogCMBaUupn5w", "name": "Satya Sanatan"},
    {"id": "UCYxHOlAIj7jViwdwV8dLA2A", "name": "Satya Tiwari"},
    {"id": "UCvXXqqFxmyI0YFewhOMJqxQ", "name": "Swarajya Mag"},
    {"id": "UCwSPxg9bl8zAFBr5KlUiaWw", "name": "Sushant Sinha"},
    {"id": "UC5J3k88h0uvSW1R_rymKirQ", "name": "Tahir Gora Channel"},
    {"id": "UCZz8q2tZC7QuQiFwPKQ4Bug", "name": "TFI Global"},
    {"id": "UCppm2c5Q2OiWpaoKxAxlOpA", "name": "TFI Post"},
    {"id": "UCIzXtOOd1y7pQFUdQhpoXaw", "name": "The Abhishek Tiwary Show"},
    {"id": "UCmjIcELD07cOV3YRPbjUJfQ", "name": "The Alternate Media"},
    {"id": "UCKPxuul6zSLAfKSsm123Vww", "name": "The Carvaka Podcast"},
    {"id": "UC1bUswUinAEFYaRQFvAKjPA", "name": "The Chanakya Dialogues Hindi"},
    {"id": "UCHChNsBtUQNlo8ysKVtNTPA", "name": "Mr Frustrated Indian"},
    {"id": "UCZjxPbi3AeB6YGKCfQ2TroQ", "name": "The Jaipur Dialogues"},
    {"id": "UC8QMsdKfiLshtzPz8XosmYg", "name": "The Manish Thakur Show"},
    {"id": "UC7SuJ7R6oSftWO3v8qWc66Q", "name": "New India Junction"},
    {"id": "UCaf0wu3R1I6MdXG_upOk2vw", "name": "The News Exclusive"},
    {"id": "UCs0kMbzhUYV2lhIV7xoWhoA", "name": "Sham Sharma Show"},
    {"id": "UCUM2qwOfZosAf55s66FsGbQ", "name": "Sham Sharma Show Global"},
    {"id": "UCQQCC-eRivp5EsSaWxX3dKg", "name": "Liberal Hindu"},
    {"id": "UCeYEL4fZfKX73afwk-UEwiw", "name": "Tufail Chaturvedi"},
    {"id": "UChYyq0Rp017VYEQzrxOuSmQ", "name": "Upword"},
    {"id": "UCUOjpYruRCB61RnB846trCQ", "name": "Vaad"},
    {"id": "UC7M5itWPv27aoceDjmpU_HA", "name": "Vijay Sardana Insights"},
    {"id": "UCvjqPU2VieP_BtYNtnrNatQ", "name": "VK News Official"},
    {"id": "UCEVPHMSoBvAtmG5rT6WZRow", "name": "We Support Pushpendra Kulshrestha"},
    {"id": "UCUwiVO9Uq7ks1LWHHY7ZARQ", "name": "Webdunia Hindi"},
    {"id": "UCLqB0xmK9YkwAmHtbuwOdwA", "name": "The Hindu Cafe"},
    {"id": "UCcnwa6E4BwDJKeATB6tqmsQ", "name": "Coffee with Sumeet Jain"},
    {"id": "UCSvQIaXSik2emJ83jlwvQLQ", "name": "Bidhuri Rishabh"},
    {"id": "UCxPLPjgt-RHxUliIrGrSesQ", "name": "Baba ki Khari Khoti"},
    {"id": "UCgQRMdlDCV1f83MjIJb3LKQ", "name": "Pulkit NPC"},
    {"id": "UCGZgJ4bM3Kc0owkF4pvrMfw", "name": "Vyalok Pathak"},
    {"id": "UCio2EyNIItdER5t1obHTtSw", "name": "The Rajdharma"},
]

HINDI_LEFT_OPINION_CHANNELS = []  # to be added

BENGALI_OPINION_CHANNELS = [
    {"id": "UCWWq6nFnUjje9RvGwYlIGTg", "name": "Arambagh TV"},
    {"id": "UCrp7axFgr0WTbFWybKFKZlQ", "name": "Campaigncalling Media"},
    {"id": "UC9YivGoN6UKWkl0k-8G1qyQ", "name": "Hothat Jodi Uthlo Kotha"},
    {"id": "UCEQSkASTH0bkG0AZ1kH8bhw", "name": "The News Bangla"},
    {"id": "UCefT7v-iDwAzbqQToY36mJw", "name": "Bongo TV"},
    {"id": "UCtODtHGNwmdSv7i5hekjrgA", "name": "Songe Adwitiya"},
    {"id": "UCvIgNfsMR3NfHYYLdikgUNA", "name": "Priyo Bandhu Media"},
    {"id": "UCqWuDZeimaWOI9TiDvZixAw", "name": "Madhyom"},
    {"id": "UCMi9LIv1yzHfGAIqnKZUfGA", "name": "Sanmoy Banerjee"},
    {"id": "UCkrE4tdQ4k8CLLOLAMQcftg", "name": "Jukti Tarko Songe Arka"},
    {"id": "UC6fbfKjLexg1nPf5NFK-QGQ", "name": "Shibam Das"},
    {"id": "UCgU5Ue1-bAtQb9xnK6q1zrA", "name": "Rudra Barta"},
    {"id": "UCRaZiQnlXlyxfwJYOyanC2w", "name": "India Hood"},
    {"id": "UC7KxtLAJdN9XvdOmbYj68Mg", "name": "Piglu 00"},
    {"id": "UCRqIKi1E-x69KBup7eyW0pQ", "name": "EVM News"},
    {"id": "UCd4Jgxg4VD-yTS30qAoMTCQ", "name": "Pinak Ki Bolche"},
    {"id": "UCKRhTf6EV4_E4vgRxah-CaA", "name": "Perfect Politics"},
    {"id": "UCSVHI858cXeEFUk8_G4tCKw", "name": "Political Daily"},
    {"id": "UC1FIRmUtxF6Yw4Y3CYjNBvw", "name": "SimpleASabc"},
    {"id": "UC9Ea502V2IJnBve8i7tdJ8w", "name": "Jagran Bangla"},
    {"id": "UCAjdUae-6-STu4AUY9VwBbw", "name": "News 16 Bharat"},
    {"id": "UCQFKW0TwxonvjVNz-vLjXWg", "name": "Speak U Bengal"},
    {"id": "UC_I5ulyzUKzgzqF46yR2WdA", "name": "The Digital Virus"},
    {"id": "UCTzlSKaQSljrTTruodTJJMQ", "name": "CM News Media"},
    {"id": "UC2V1Hw_vCqWUbsUT_P-Xmpg", "name": "Nabanna Nimantran"},
    {"id": "UCxhf49wOiJeWiUzkBfuAEcQ", "name": "The Wall News"},
    {"id": "UCcsSoLkRobqNFfkS8TDg5qw", "name": "Sanmoy Speaks"},
    {"id": "UCdbT6v89UrmdKIob0tGUEXw", "name": "Bibidho News"},
    {"id": "UCPxBRy06Xut2pZ_Wgl528yg", "name": "Political Guru"},
    {"id": "UCVKZTEIghULaS-HFhjyWjlg", "name": "Banglasphere"},
]
