BANGLADESH_NEWS_CHANNELS = [
    {"id": "UCNUFterLJ9vpFZZ0try7sLA", "name": "BD News"},
    {"id": "UCbgcYEdMsuypG2NJ-znBp3w", "name": "BD News"},
    {"id": "UCHLqIOMPk20w-6cFgkA90jw", "name": "BD News"},
    {"id": "UCO_uhQ1EFB9bwqnV6i7UHnw", "name": "BD News"},
    {"id": "UCPREnbhKQP-hsVfsfKP-mCw", "name": "BD News"},
    {"id": "UCWVqdPTigfQ-cSNwG7O9MeA", "name": "BD News"},
    {"id": "UCUDQdVsKssximyFwg4IxnOQ", "name": "BD News"},
    {"id": "UC2P5Fd5g41Gtdqf0Uzh8Qaw", "name": "BD News"},
    {"id": "UCATUkaOHwO9EP_W87zCiPbA", "name": "BD News"},
    {"id": "UC8NcXMG3A3f2aFQyGTpSNww", "name": "BD News"},
    {"id": "UCig6MgICx3g8p3IHZM45oEA", "name": "BD News"},
    {"id": "UCRorOml5erbG8j_uqh8Sx6g", "name": "BD News"},
    {"id": "UCmCCTsDl-eCKw91shC7ZmMw", "name": "BD News"},
    {"id": "UCrqpxgInFaw4uVQpdqvZhxA", "name": "BD News"},
    {"id": "UC0xxD1tl7DZa1N7mZcibzJA", "name": "BD News"},
    {"id": "UCuXsj5ENgvmNyReMYBJvRDw", "name": "BD News"},
    {"id": "UCuzoe7B4zeAKhdhcNKsQJ1w", "name": "BD News"},
    {"id": "UCBQxpxkI2qLRAFR_6PNdwIA", "name": "BD News"},
    {"id": "UCWzOfBhVmuRmAd5bzxXP2CA", "name": "BD News"},
    {"id": "UCKbhCXpZwAmFN4UHeT8HTjA", "name": "BD News"},
    {"id": "UCrbWzP4kllmFMr_uWphAbXg", "name": "BD News"},
    {"id": "UCt8llfhkf9LRzjTEnbG2qnQ", "name": "BD News"},
    {"id": "UCJerhfpMLFWhuYiHVJb2mHw", "name": "BD News"},
    {"id": "UCHR-p802PibDYG1btNJcOew", "name": "BD News"},
    {"id": "UC-Gc1p3IRxvK375DAKnoJ7A", "name": "BD News"},
    {"id": "UCeG7m5-AJ4I0H4EIleIty4Q", "name": "BD News"},
    {"id": "UCRt2klyaxgx89vPF8cFMfnQ", "name": "BD News"},
    {"id": "UC9Rgo0CrNyd7OWliLekqqGA", "name": "BD News"},
    {"id": "UCDj9HHrRUzlsTuPQN0PHxjw", "name": "BD News"},
    {"id": "UCFRxWDF-ZHgs0X6PckJVC9A", "name": "BD News"},
    {"id": "UC2HXZuHFLddZib4gDl1m6cA", "name": "BD News"},
    {"id": "UClVZ6GRSWj2oEUQQCW_xdaw", "name": "BD News"},
    {"id": "UCsBqX8QguRdkawdlNbIL1dw", "name": "BD News"},
    {"id": "UC7PwfNI2zuokhCctN9VymLg", "name": "BD News"},
    {"id": "UC2lQ-lzB4_fIShEKm89U5hg", "name": "BD News"},
    {"id": "UCTSvHZkOStz5Ak2J_q6YRlA", "name": "BD News"},
    {"id": "UCjFMRqrsABGBh-6eFUlMuAA", "name": "BD News"},
    {"id": "UCN6sm8iHiPd0cnoUardDAnw", "name": "BD News"},
    {"id": "UCtqvtAVmad5zywaziN6CbfA", "name": "BD News"},
    {"id": "UCA4y9g_GRdNrZLH_u5LLSdw", "name": "BD News"},
    {"id": "UCUvXoiDEKI8VZJrr58g4VAw", "name": "BD News"},
    {"id": "UC9zgYOQB6zkleAQjW53DLeQ", "name": "BD News"},
    {"id": "UCUNEzmQ3zcifrhn0HwCgjYg", "name": "BD News"},
    {"id": "UCO2Ds5LXqzQSH6HMnJFWYBA", "name": "BD News"},
    {"id": "UClzwimpLoZu9us9MwalLbtA", "name": "BD News"},
    {"id": "UC9b_MnX3HN9ABYT89QqYMTw", "name": "BD News"},
    {"id": "UCl13d2BTcnn_wQmlpWV_Ctw", "name": "BD News"},
    {"id": "UCKSJ5rTXq-pYgAmAOhVS_zQ", "name": "BD News"},
    {"id": "UCWJkfdG6J2HUxOHrORuHZ2g", "name": "BD News"},
    {"id": "UCVdS5j1VpsBx40kiqozkuGA", "name": "BD News"},
    {"id": "UCxHoBXkY88Tb8z1Ssj6CWsQ", "name": "BD News"},
    {"id": "UCrMMnV7NJQn5MOvzSukHbHQ", "name": "BD News"},
    {"id": "UChPD2BQ2dJ-w00klQQkc-Qg", "name": "BD News"},
    {"id": "UCVg6qg-ZeFoVHUFSFk7lKGg", "name": "BD News"},
    {"id": "UCVBUCoStRou7DZtlTxmhAmQ", "name": "BD News"},
    {"id": "UCp0svklvXrphG3A6jItBcNQ", "name": "BD News"},
    {"id": "UC0g7R-oqBXYZDIE8yPgT6rA", "name": "BD News"},
    {"id": "UCz94DIR9Ma9IrRwcOoQJYeA", "name": "BD News"},
    {"id": "UCgsp7WfVvh94TiDoPagPkrg", "name": "BD News"},
    {"id": "UC5csuMwNPRsU9AWOSr94wmg", "name": "BD News"},
    {"id": "UCv_oQ-sRZoJdEX4K5fQ6q6w", "name": "BD News"},
    {"id": "UCYvHZshicTvoECr9J88TCvQ", "name": "BD News"},
    {"id": "UCz8RV3ySqP3SmgQFZzceVPg", "name": "BD News"},
    {"id": "UCFihYNaJ9epsrwWc4FVM2vA", "name": "BD News"},
    {"id": "UCKs4WACazSqlI7E09GZm5cA", "name": "BD News"},
    {"id": "UCjbhem0DnZTrOjdoHBT5VZQ", "name": "BD News"},
    {"id": "UCMMCiB3he7fwFUvLBRMTaZQ", "name": "BD News"},
    {"id": "UCIXugjH-g5bFUqLoYRgiSbg", "name": "BD News"},
    {"id": "UCnetEdV8EwzGn36f3pq50ZA", "name": "BD News"},
]

WORLD_NEWS_CHANNELS = [
    # Wire Services
    {"id": "UChqUTb7kYRX8-EiaN3XFrSQ", "name": "Reuters"},
    {"id": "UC52X5wxOL_s5yw0dQk7NtgA", "name": "Associated Press"},
    {"id": "UC86dbj-lbDks_hZ5gRKL49Q", "name": "AFP News Agency"},
    # Global Broadcasters
    {"id": "UC16niRr50-MSBwiO3YDb3RA", "name": "BBC News"},
    {"id": "UCNye-wNBqNL5ZzHSJj3l8Bg", "name": "Al Jazeera English"},
    {"id": "UCQfwfsi5VrQ8yKZ-UWmAEFg", "name": "France 24 English"},
    {"id": "UCknLrEdhRCp1aegoMqRaCZg", "name": "DW News"},
    {"id": "UCSrZ3UV4jOidv8ppoVuvW9Q", "name": "Euronews English"},
    {"id": "UC7fWeaHhqgM4Ry-RMpM2YYw", "name": "TRT World"},
    {"id": "UCoMdktPbSTixAyNGwb-UYkQ", "name": "Sky News"},
    {"id": "UCTrQ7HXWRRxr7OsOtodr2_w", "name": "Channel 4 News"},
    # USA
    {"id": "UCBi2mrWuNuyYy4gbM6fU18Q", "name": "ABC News"},
    {"id": "UC8p1vwvWtl6T73JiExfWs1g", "name": "CBS News"},
    {"id": "UCIALMKvObZNtJ6AmdCLP7Lg", "name": "Bloomberg TV"},
    {"id": "UC6ZFN9Tx6xh-skXCuRHCDpQ", "name": "PBS NewsHour"},
    # Asia-Pacific
    {"id": "UC83jt4dlz1Gjl58fzQrrKZg", "name": "CNA"},
    {"id": "UCSPEjw8F2nQDtmUKPFNF7_A", "name": "NHK World"},
    {"id": "UCzznO4xSV8BKnUBPyswtCUw", "name": "ARIRANG News"},
    {"id": "UCVgO39Bk5sMo66-6o6Spn6Q", "name": "ABC News Australia"},
    {"id": "UCO0akufu9MOzyz3nvGIXAAw", "name": "Sky News Australia"},
    # Middle East
    {"id": "UCvHDpsWKADrDia0c99X37vg", "name": "i24 News"},
    {"id": "UCI8DegIWgK51cGakXcf1dOQ", "name": "Arab News"},
    # Africa
    {"id": "UCEXGDNclvmg6RW0vipJYsTQ", "name": "Channels TV"},
    {"id": "UCgp4A6I8LCWrhUzn-5SbKvA", "name": "TVC News Nigeria"},
    {"id": "UCKVsdeoHExltrWMuK0hOWmg", "name": "KTN News Kenya"},
    {"id": "UCqBJ47FjJcl61fmSbcadAVg", "name": "NTV Kenya"},
    {"id": "UC8yH-uI81UUtEMDsowQyx1g", "name": "SABC News"},
    # Newspapers
    {"id": "UCqnbDFdCpuN8CMEg0VuEBqA", "name": "New York Times"},
    {"id": "UCHd62-u_v4DvJ8TCFtpi4GA", "name": "Washington Post"},
    {"id": "UCK7tptUDHh-RYDsdxO1-5QQ", "name": "Wall Street Journal"},
    {"id": "UCHpw8xwDNhU9gdohEcJu4aA", "name": "The Guardian"},
    {"id": "UCoUxsWakJucWg46KW5RsvPw", "name": "Financial Times"},
    {"id": "UCshwRhftzkiov5wKR7M_LsQ", "name": "The Independent"},
    {"id": "UC0p5jTq6Xx_DosDFxVXnWaQ", "name": "The Economist"},
    {"id": "UC4p_I9eiRewn2KoU-nawrDg", "name": "Straits Times"},
    {"id": "UC4SUWizzKc1tptprBkWjX2Q", "name": "South China Morning Post"},
    # South Asia
    {"id": "UCuOtdpOPjHeoEAT4i44mVOg", "name": "Ada Derana English"},
]

NATIONAL_ENGLISH_CHANNELS = [
    {"id": "UCef1-8eOpJgud7szVPlZQAQ", "name": "CNN-News18"},
    {"id": "UCwqusr8YDwM-3mEYTDeJHzw", "name": "Republic World"},
    {"id": "UCckHqySbfy5FcPP6MD_S-Yg", "name": "Times of India"},
    {"id": "UC6RJ7-PaXg6TIH2BzZfTV7w", "name": "Times Now"},
    {"id": "UCtFQDgA8J8_iiwc5-KoAQlg", "name": "ANI News"},
    {"id": "UCz8QaiQxApLq8sLNcszYyJw", "name": "Firstpost"},
    {"id": "UCYPvAwZP8pZhSMW8qs7cVCw", "name": "India Today"},
    {"id": "UCm7lHFkt2yB_WzL67aruVBQ", "name": "HT Videos"},
    {"id": "UCZFMm1mMw0F81Z37aaEzTUA", "name": "NDTV"},
    {"id": "UC_gUM8rL-Lrg6O3adPW9K1g", "name": "WION"},
    {"id": "UCc8J8UvzwMZHnO0MX1NTmSw", "name": "The Tribune"},
    {"id": "UCytSP0M0Jdnw6qIy3Y-nTig", "name": "NewsX"},
    {"id": "UCUI9vm69ZbAqRK3q3vKLWCQ", "name": "Mint"},
    {"id": "UCJEDFSxHHOW1PpBccdSxOTA", "name": "Indian Express"},
    {"id": "UCqTa3sNT6SfiQ2DQK_kuWlA", "name": "Oneindia"},
    {"id": "UCuyRsHZILrU7ZDIAbGASHdA", "name": "The Print"},
    {"id": "UCWCEYVwSqr7Epo6sSCfUgiw", "name": "Mirror Now"},
    {"id": "UCLIMdoS-InL1-GIBUKSvydg", "name": "Mid-Day"},
    {"id": "UC3njZ48-FDxLleBYaP0SZIg", "name": "The Hindu"},
    {"id": "UCQtVJ-76KjPds9evTODkq-A", "name": "New Indian Express"},
    {"id": "UCHDXXHPrz-1GVbK_qk82hBQ", "name": "Deccan Herald"},
    {"id": "UCw8Fc5R0Q5yyS3KrDCPM3xg", "name": "Times Now World"},
    {"id": "UCRK4FDIkUyslEAUdyRDdCtQ", "name": "News9 Live"},
    {"id": "UCJFOER35ggIWwsXh2ZDnqyg", "name": "The Economic Times"},
]

NATIONAL_HINDI_CHANNELS = [
    {"id": "UCt4t-jeY85JegMlZ-E5UWtA", "name": "Aaj Tak"},
    {"id": "UCx8Z14PpntdaxCt2hakbQLQ", "name": "The Lallantop"},
    {"id": "UCttspZesZIDEwwpVIgoZtWQ", "name": "India TV"},
    {"id": "UCRWFSbif-RFENbBrSiez1DA", "name": "ABP News"},
    {"id": "UCPP3etACgdUWvizcES1dJ8Q", "name": "News18 India"},
    {"id": "UC9CYT9gSNLevX5ey2_6CK0Q", "name": "NDTV India"},
    {"id": "UCOutOIcn_oho8pyVN3Ng-Pg", "name": "TV9 Bharatvarsh"},
    {"id": "UCMk9Tdc-d1BIcAFaSppiVkw", "name": "Times Now Navbharat"},
    {"id": "UC531MlZA5LUbeGwEN_zcppw", "name": "News18 Bihar Jharkhand"},
    {"id": "UC7wXt18f2iA3EDXeqAVuKng", "name": "Republic Bharat"},
    {"id": "UCIvaYmXn910QMdemBG3v1pQ", "name": "Zee News"},
    {"id": "UCKwucPzHZ7zCUIf7If-Wo1g", "name": "DD News"},
    {"id": "UC8eEZ-l5z_zzG8GT0Tu0PaA", "name": "India Dot Com"},
    {"id": "UCP_wvXToU5ohFLbTAkatvsw", "name": "Amar Ujala"},
    {"id": "UCCJRFl1Qjo83GG_09U-DIBA", "name": "Hindustan"},
    {"id": "UCvxi7_X1VSaMr_osIamYNaw", "name": "NMF News"},
    {"id": "UCOjgc1p2hJ4GZi6pQQoXWYQ", "name": "Oneindia Hindi"},
    {"id": "UCsNdeLwEZf86swPD3qJJ7Dw", "name": "News Nation"},
    {"id": "UCUGwnDFBHY52YhgVjn-Tvww", "name": "ABP Ganga"},
    {"id": "UCSKgOW8Pg_eZymYJyJc432g", "name": "Dainik Jagran"},
    {"id": "UCafYgzpyw7aIUYOLjjADu7w", "name": "News18 UP Uttarakhand"},
    {"id": "UCBwc2cbPpvxNCNEI2-8YrqQ", "name": "News18 MP Chhattisgarh"},
    {"id": "UCl8wUKzoUVzg7U6ky1ZR8hQ", "name": "Navbharat Times"},
    {"id": "UC_cZYFovNQTsKw1ZLmO_AMA", "name": "First India News"},
    {"id": "UClmlqOOktUTpfW0EkTiqSjQ", "name": "Aaj Tak HD"},
    {"id": "UCmphdqZNmqL72WJ2uyiNw5w", "name": "ABP Live"},
]

BENGALI_CHANNELS = [
    {"id": "UCv3rFzn-GHGtqzXiaq3sWNg", "name": "ABP Ananda"},
    {"id": "UCdF5Q5QVbYstYrTfpgUl0ZA", "name": "Zee 24 Ghanta"},
    {"id": "UCHCR4UFsGwd_VcDa0-a4haw",  "name": "TV9 Bangla"},
    {"id": "UCbf0XHULBkTfv2hBjaaDw9Q",  "name": "News18 Bangla"},
    {"id": "UCajVjEHDoVn_AHsunUZz_EQ",  "name": "Republic Bangla"},
    {"id": "UCdfOu3dJAYCc99mUy8hyfMw",  "name": "Aaj Tak Bangla"},
    {"id": "UCJ3I6MHOz5exARlTW_meOGQ",  "name": "Calcutta News"},
    {"id": "UC7GSS1hr39KcjdsKqAO76aQ",  "name": "Asianet News Bangla"},
    {"id": "UCHHYiu-zVZ307SN_gNqr88Q",  "name": "Tribe TV"},
    {"id": "UCe4GErYKwpMUJWZpxOiATYA",  "name": "DD Bangla News"},
    {"id": "UCycQauzU5n3DwQdgk3cw91A",  "name": "R Plus News 24x7"},
    {"id": "UC-drIvdQ0sZlyPXCizj4vgQ",  "name": "News Time Bangla"},
    {"id": "UC75RbtivNkL0XLElFAxg_zA",  "name": "High News"},
    {"id": "UCESY9RzEDPsb9lRLMxAirwQ",  "name": "Anandabazar Patrika"},
    {"id": "UCWoPoR2Jho2tbFV4TttLNdA",  "name": "Bartaman"},
    {"id": "UCPYZ_TMaFSsAGyedFpwyufA",  "name": "Ei Samay"},
    {"id": "UCkwTQGJelg1F-gV2ZmfPg8Q",  "name": "Aajkaal"},
    {"id": "UCLPCvTftdZpZQSM-mckfqXQ",  "name": "Sangbad Pratidin"},
    {"id": "UCdx_kjAFLinvdnEkdklgoNQ",  "name": "Ganashakti"},
    {"id": "UCXDw7ADM9CnoGPEk3aSsHaQ",  "name": "Uttar Banga Sambad"},
    {"id": "UCpthbAb5DDRfcG68VMn6q0g",  "name": "Indian Express Bangla"},
]

HINDI_RIGHT_OPINION_CHANNELS = [
    {"id": "UCloWBBZ3E9b9NGW3r30DN5A", "name": "AKTK"},
    {"id": "UCsDTy8jvHcwMvSZf_JGi-FA", "name": "Abhi and Niyu"},
    {"id": "UC2bBsPXFWZWiBmkRiNlz8vg", "name": "Abhijit Chavda"},
    {"id": "UCsu4YmPw7E9PyGrWQG6fT9g", "name": "Advaita Kala Now"},
    {"id": "UC0PV5M3VlgXlP0wUqTJIIeQ", "name": "Ajeet Bharti"},
    {"id": "UCgX-nwxANLWE1d087jWlKQQ", "name": "Amber Zaidi Official"},
    {"id": "UCPJ_UzD4PEC-_vwN32amlIQ", "name": "Open Letter"},
    {"id": "UCNd46hD9lsr9NDliR--u4KQ", "name": "Anju Pankaj"},
    {"id": "UCp-1mZlbdVhj0j49m4bPspA", "name": "Anuj Awasthi"},
    {"id": "UC_gVr8TXCS0METhTLsps-sA", "name": "Apka Akhbar"},
    {"id": "UCD5W5_9TVSsIgYIkt47sWgw", "name": "Ashwini Upadhyay"},
    {"id": "UCfBfBd-1kvCOPxVll8tBJ9Q", "name": "Bharat Vaarta"},
    {"id": "UCnx0p9wzQXoBXOCRIeUfUrg", "name": "Budhi Media"},
    {"id": "UCGaOkbpMXx4j07kxQYpxFDA", "name": "Capital TV India"},
    {"id": "UCu3ix1BLMKTIIcjjXo-4X3w", "name": "Centre for Indic Studies"},
    {"id": "UC4vgB_qDWH3-RrgHE1isOYQ", "name": "DK Dubey"},
    {"id": "UCVVRDJbTe6q6FJRR4m3h3_A", "name": "DEF Talks by Aadi"},
    {"id": "UC4Yk3q9vmANVVMXOST89kxQ", "name": "Defensive Offence"},
    {"id": "UCwmgD2dyF1cJEFoQhjMrGrA", "name": "Do News Today"},
    {"id": "UCQlshr3xpvpcCeAZvGRz9Zg", "name": "Engineer Reveals"},
    {"id": "UCYldxBSTvUwJiw3haNlbccw", "name": "Rizwan Ahmed Adv"},
    {"id": "UC_hqg81N9k0R6xna0aNGoPw", "name": "Gunners Shot"},
    {"id": "UCVlWRiW6C6WVgOnHv4xSUjw", "name": "Harish Burnwal"},
    {"id": "UC0BQdLALVmrUeX5wvsEOEdA", "name": "Media Harsh VT"},
    {"id": "UCNViMnyO8ZaPyrGQfSn8xAA", "name": "HDV News Official"},
    {"id": "UCpelPgePHrkrFYGgtFD8xsQ", "name": "India In Details"},
    {"id": "UCE_F0nmdE-4puiTvzVh10bg", "name": "India This Week by Amana Khalid"},
    {"id": "UCk85J3pqkn1y--k2wNMbthA", "name": "Rajiv Malhotra Official"},
    {"id": "UCnZhp2ugahf_NZN-RuT09HQ", "name": "Ishkaran Singh Bhandari"},
    {"id": "UCK-HHyVCfKYzhxVOJgBt73w", "name": "Keerthika Govindhasamy"},
    {"id": "UCmkmN_OMZP8pXmjvN8fNY7w", "name": "Key Fact"},
    {"id": "UCln9HY5pf2oXm0x2GwUfrHQ", "name": "Mahamtb"},
    {"id": "UCdnFIeHJGhSjRoLvTZpYldw", "name": "Neeraj Atri"},
    {"id": "UCVErsRbJ_QXpGoro5ri0Lww", "name": "Nitin Shukla Live"},
    {"id": "UCr6z9q34HbkngcjkhWV1_lA", "name": "Omkar Chaudhary Show"},
    {"id": "UCWt3UbeNDgNd97-VREMtS4g", "name": "OpIndia"},
    {"id": "UCt-ybO9Kw9QqG9Ts_YaPJgA", "name": "Spy Games Pavneet"},
    {"id": "UC5oAOrsfqTxLOmFNuK_S8ug", "name": "PGurus1"},
    {"id": "UCK3NMOnCHSm87Ga7ktoEyUA", "name": "PGurus"},
    {"id": "UCD72C2pY5ua8zOnnk5YAEqw", "name": "Praarabdh"},
    {"id": "UCefJQ7fUmr_gm6OKfAjRDIQ", "name": "Prachyam"},
    {"id": "UC1hHsI_EVwDxBTS0UajEPQA", "name": "Public 24x7"},
    {"id": "UCoDiyU0xjSXJhmKJCqLeCNQ", "name": "Pyara Hindustan"},
    {"id": "UCNthz4aHxOekgLKDDERQbAA", "name": "Samrat Bhai"},
    {"id": "UC3nhAUpe7aBm1rFCBgoWWcA", "name": "Sangam Talks"},
    {"id": "UCAAkERuVmC4ogCMBaUupn5w", "name": "Satya Sanatan"},
    {"id": "UCYxHOlAIj7jViwdwV8dLA2A", "name": "Satya Tiwari"},
    {"id": "UCvXXqqFxmyI0YFewhOMJqxQ", "name": "Swarajya Mag"},
    {"id": "UCwSPxg9bl8zAFBr5KlUiaWw", "name": "Sushant Sinha"},
    {"id": "UC5J3k88h0uvSW1R_rymKirQ", "name": "Tahir Gora Channel"},
    {"id": "UCZz8q2tZC7QuQiFwPKQ4Bug", "name": "TFI Global"},
    {"id": "UCppm2c5Q2OiWpaoKxAxlOpA", "name": "TFI Post"},
    {"id": "UCIzXtOOd1y7pQFUdQhpoXaw", "name": "The Abhishek Tiwary Show"},
    {"id": "UCmjIcELD07cOV3YRPbjUJfQ", "name": "The Alternate Media"},
    {"id": "UCKPxuul6zSLAfKSsm123Vww", "name": "The Carvaka Podcast"},
    {"id": "UC1bUswUinAEFYaRQFvAKjPA", "name": "The Chanakya Dialogues Hindi"},
    {"id": "UCHChNsBtUQNlo8ysKVtNTPA", "name": "Mr Frustrated Indian"},
    {"id": "UCZjxPbi3AeB6YGKCfQ2TroQ", "name": "The Jaipur Dialogues"},
    {"id": "UC8QMsdKfiLshtzPz8XosmYg", "name": "The Manish Thakur Show"},
    {"id": "UC7SuJ7R6oSftWO3v8qWc66Q", "name": "New India Junction"},
    {"id": "UCaf0wu3R1I6MdXG_upOk2vw", "name": "The News Exclusive"},
    {"id": "UCs0kMbzhUYV2lhIV7xoWhoA", "name": "Sham Sharma Show"},
    {"id": "UCUM2qwOfZosAf55s66FsGbQ", "name": "Sham Sharma Show Global"},
    {"id": "UCQQCC-eRivp5EsSaWxX3dKg", "name": "Liberal Hindu"},
    {"id": "UCeYEL4fZfKX73afwk-UEwiw", "name": "Tufail Chaturvedi"},
    {"id": "UChYyq0Rp017VYEQzrxOuSmQ", "name": "Upword"},
    {"id": "UCUOjpYruRCB61RnB846trCQ", "name": "Vaad"},
    {"id": "UC7M5itWPv27aoceDjmpU_HA", "name": "Vijay Sardana Insights"},
    {"id": "UCvjqPU2VieP_BtYNtnrNatQ", "name": "VK News Official"},
    {"id": "UCEVPHMSoBvAtmG5rT6WZRow", "name": "We Support Pushpendra Kulshrestha"},
    {"id": "UCUwiVO9Uq7ks1LWHHY7ZARQ", "name": "Webdunia Hindi"},
    {"id": "UCLqB0xmK9YkwAmHtbuwOdwA", "name": "The Hindu Cafe"},
    {"id": "UCcnwa6E4BwDJKeATB6tqmsQ", "name": "Coffee with Sumeet Jain"},
    {"id": "UCSvQIaXSik2emJ83jlwvQLQ", "name": "Bidhuri Rishabh"},
    {"id": "UCxPLPjgt-RHxUliIrGrSesQ", "name": "Baba ki Khari Khoti"},
    {"id": "UCgQRMdlDCV1f83MjIJb3LKQ", "name": "Pulkit NPC"},
    {"id": "UCGZgJ4bM3Kc0owkF4pvrMfw", "name": "Vyalok Pathak"},
    {"id": "UCio2EyNIItdER5t1obHTtSw", "name": "The Rajdharma"},
]

HINDI_LEFT_OPINION_CHANNELS = []  # to be added

MYANMAR_NEWS_CHANNELS = [
    # English-language channels only
    {"id": "UCdI0UA27karDChnhnboHmqQ", "name": "DVB English"},
    {"id": "UCgEI7TvwuNGVGpd1M0icWJQ", "name": "The Irrawaddy"},
]

NEPAL_NEWS_CHANNELS = [
    {"id": "UCMDzPE_7fcZSRJgpwIVor_A", "name": "Avenues TV"},
    {"id": "UC4h-FP0sqCPzFikmZqF0ZIA", "name": "ABC News Nepal"},
    {"id": "UCVsE1h7d6-NnaSg2JQ5vRQw", "name": "TV Annapurna"},
    {"id": "UCNSPYrl_sdPfOIS4e1HjhMg", "name": "TV Today HD"},
    {"id": "UC7JGxk_AFlBz5pyXPuQMELg", "name": "OTV Nepal"},
    {"id": "UCR0sb6TDx2vY0DGsLlDr5BA", "name": "Sagarmatha TV"},
    {"id": "UCXHgSsTbbojsyot6Kg_q2mg", "name": "Nepal Live"},
    {"id": "UCY0zpSUoxHZNHGq9-926G4w", "name": "Global TV HD"},
    {"id": "UCZlRPQfqzssWXtTin21lwlg", "name": "Danfe TV"},
    {"id": "UCtjmWttibtOsdow5lYBD-7A", "name": "Mountain TV"},
    {"id": "UCa1-bet7aevH-YmtPhqdwtQ", "name": "Fewa TV"},
    {"id": "UCKCKxATff7qnaEu7Wd7lZbQ", "name": "Everest Nepal TV"},
    {"id": "UCDFqB5h4nbpZTaU7QQ3u3cw", "name": "BG TV Nepal"},
    {"id": "UCxG_3NG1uWy4_x1nMj-Wdwg", "name": "Good TV"},
    {"id": "UCZb6R17u4dLtR_v6yoIM2Ig", "name": "Horizon TV Nepal"},
    {"id": "UCa9wigEw31xDMh_nrscmL6g", "name": "BBC Nepali"},
    {"id": "UCPjHEeafcMdr-balIMiEwrg", "name": "Setopati"},
    {"id": "UCQZ18Tr_bEqo6-0S9z1psPw", "name": "Nepal Times"},
    {"id": "UCguFuMcHqNX4qF-JaJg9KKw", "name": "Lokantar TV"},
    {"id": "UCHfEz1mbYhQR-GxVi1RrNXw", "name": "Reporters Nepal"},
]

PAKISTAN_NEWS_CHANNELS = [
    {"id": "UC_vt34wimdCzdkrzVejwX9g", "name": "Geo News"},
    {"id": "UCMmpLL2ucRHAXbNHiCPyIyg", "name": "ARY News"},
    {"id": "UCJekW1Vj5fCVEGdye_mBN6Q", "name": "SAMAA TV"},
    {"id": "UCnMBV5Iw4WqKILKue1nP6Hg", "name": "Dunya News"},
    {"id": "UCz2yxQJZgiB_5elTzqV7FiQ", "name": "BOL News"},
    {"id": "UCsgC5cbz3DE2Shh34gNKiog", "name": "92 News HD"},
    {"id": "UCTur7oM6mLL0rM2k0znuZpQ", "name": "Express News"},
    {"id": "UC35KuZBNIj4S5Ls0yjY-UHQ", "name": "GNN"},
    {"id": "UCElJZvY_RVra6qjD8WSQYog", "name": "Public News"},
    {"id": "UC-an6pHQfTVZXgrLP0p1EGA", "name": "Capital TV"},
    {"id": "UC0CbUVRC1d1RvunYbp3w2qQ", "name": "Lahore News HD"},
    {"id": "UCaxR-D8FjZ-2otbU0_Y2grg", "name": "Dawn News"},
    {"id": "UCAsvFcpUQegneSh0QAUd64A", "name": "Neo News"},
    {"id": "UCgBAPAcLsh_MAPvJprIz89w", "name": "Aaj TV"},
    {"id": "UCCEMt2W7Y8qXkLSTkr082mw", "name": "Khyber News"},
    {"id": "UC7EDIC3ONWZpN3DLkRzmhww", "name": "AAP News"},
    {"id": "UC5mwDEzm4FzXKoHPBDnuUQQ", "name": "Abb Tak"},
    {"id": "UCjHWKUbljF4hp3s5PbgK9uA", "name": "News One"},
    {"id": "UC5RvV_LtR1dxPCVFGw6dxXA", "name": "PTV News"},
    {"id": "UC6XLG5YjZfK1p5oY5MJ3NMw", "name": "GTV News HD"},
    {"id": "UCAT-k0v_xVXOmLgNwa_dzdw", "name": "7 News Pakistan"},
    {"id": "UCzVdIJeAwQfBZbG_8AOXgBw", "name": "Naya Daur"},
    {"id": "UCICSlkaHBZwU_86JrIbeoCQ", "name": "Duniya TV"},
    {"id": "UCAvhohWtYwPdpKVGiMkkKOQ", "name": "Independent Urdu"},
    {"id": "UCQDZ97IhAmyQWu3SlPspc4g", "name": "Daily Ausaf"},
    {"id": "UCvm8V4Dwtz0fbPGbpk7RYAg", "name": "BBC News Urdu"},
    {"id": "UCV1K26GOlQOB_3sRS8vDzhw", "name": "DW Urdu"},
    {"id": "UCx8MbRAMH-KNJuFLKdsmZ_w", "name": "VOA Urdu"},
]

BENGALI_OPINION_CHANNELS = [
    {"id": "UCWWq6nFnUjje9RvGwYlIGTg", "name": "Arambagh TV"},
    {"id": "UCrp7axFgr0WTbFWybKFKZlQ", "name": "Campaigncalling Media"},
    {"id": "UC9YivGoN6UKWkl0k-8G1qyQ", "name": "Hothat Jodi Uthlo Kotha"},
    {"id": "UCEQSkASTH0bkG0AZ1kH8bhw", "name": "The News Bangla"},
    {"id": "UCefT7v-iDwAzbqQToY36mJw", "name": "Bongo TV"},
    {"id": "UCtODtHGNwmdSv7i5hekjrgA", "name": "Songe Adwitiya"},
    {"id": "UCvIgNfsMR3NfHYYLdikgUNA", "name": "Priyo Bandhu Media"},
    {"id": "UCqWuDZeimaWOI9TiDvZixAw", "name": "Madhyom"},
    {"id": "UCMi9LIv1yzHfGAIqnKZUfGA", "name": "Sanmoy Banerjee"},
    {"id": "UCkrE4tdQ4k8CLLOLAMQcftg", "name": "Jukti Tarko Songe Arka"},
    {"id": "UC6fbfKjLexg1nPf5NFK-QGQ", "name": "Shibam Das"},
    {"id": "UCgU5Ue1-bAtQb9xnK6q1zrA", "name": "Rudra Barta"},
    {"id": "UCRaZiQnlXlyxfwJYOyanC2w", "name": "India Hood"},
    {"id": "UC7KxtLAJdN9XvdOmbYj68Mg", "name": "Piglu 00"},
    {"id": "UCRqIKi1E-x69KBup7eyW0pQ", "name": "EVM News"},
    {"id": "UCd4Jgxg4VD-yTS30qAoMTCQ", "name": "Pinak Ki Bolche"},
    {"id": "UCKRhTf6EV4_E4vgRxah-CaA", "name": "Perfect Politics"},
    {"id": "UCSVHI858cXeEFUk8_G4tCKw", "name": "Political Daily"},
    {"id": "UC1FIRmUtxF6Yw4Y3CYjNBvw", "name": "SimpleASabc"},
    {"id": "UC9Ea502V2IJnBve8i7tdJ8w", "name": "Jagran Bangla"},
    {"id": "UCAjdUae-6-STu4AUY9VwBbw", "name": "News 16 Bharat"},
    {"id": "UCQFKW0TwxonvjVNz-vLjXWg", "name": "Speak U Bengal"},
    {"id": "UC_I5ulyzUKzgzqF46yR2WdA", "name": "The Digital Virus"},
    {"id": "UCTzlSKaQSljrTTruodTJJMQ", "name": "CM News Media"},
    {"id": "UC2V1Hw_vCqWUbsUT_P-Xmpg", "name": "Nabanna Nimantran"},
    {"id": "UCxhf49wOiJeWiUzkBfuAEcQ", "name": "The Wall News"},
    {"id": "UCcsSoLkRobqNFfkS8TDg5qw", "name": "Sanmoy Speaks"},
    {"id": "UCdbT6v89UrmdKIob0tGUEXw", "name": "Bibidho News"},
    {"id": "UCPxBRy06Xut2pZ_Wgl528yg", "name": "Political Guru"},
    {"id": "UCVKZTEIghULaS-HFhjyWjlg", "name": "Banglasphere"},
]
