NATIONAL_ENGLISH_CHANNELS = [
    {"id": "UCef1-8eOpJgud7szVPlZQAQ", "name": "CNN-News18"},
    {"id": "UCwqusr8YDwM-3mEYTDeJHzw", "name": "Republic World"},
    {"id": "UCckHqySbfy5FcPP6MD_S-Yg", "name": "Times of India"},
    {"id": "UC6RJ7-PaXg6TIH2BzZfTV7w", "name": "Times Now"},
    {"id": "UCtFQDgA8J8_iiwc5-KoAQlg", "name": "ANI News"},
    {"id": "UCz8QaiQxApLq8sLNcszYyJw", "name": "Firstpost"},
    {"id": "UCYPvAwZP8pZhSMW8qs7cVCw", "name": "India Today"},
    {"id": "UCm7lHFkt2yB_WzL67aruVBQ", "name": "HT Videos"},
    {"id": "UCZFMm1mMw0F81Z37aaEzTUA", "name": "NDTV"},
    {"id": "UC_gUM8rL-Lrg6O3adPW9K1g", "name": "WION"},
    {"id": "UCc8J8UvzwMZHnO0MX1NTmSw", "name": "The Tribune"},
    {"id": "UCytSP0M0Jdnw6qIy3Y-nTig", "name": "NewsX"},
    {"id": "UCUI9vm69ZbAqRK3q3vKLWCQ", "name": "Mint"},
    {"id": "UCJEDFSxHHOW1PpBccdSxOTA", "name": "Indian Express"},
    {"id": "UCqTa3sNT6SfiQ2DQK_kuWlA", "name": "Oneindia"},
    {"id": "UCuyRsHZILrU7ZDIAbGASHdA", "name": "The Print"},
    {"id": "UCWCEYVwSqr7Epo6sSCfUgiw", "name": "Mirror Now"},
    {"id": "UCLIMdoS-InL1-GIBUKSvydg", "name": "Mid-Day"},
    {"id": "UC3njZ48-FDxLleBYaP0SZIg", "name": "The Hindu"},
    {"id": "UCQtVJ-76KjPds9evTODkq-A", "name": "New Indian Express"},
    {"id": "UCHDXXHPrz-1GVbK_qk82hBQ", "name": "Deccan Herald"},
    {"id": "UCw8Fc5R0Q5yyS3KrDCPM3xg", "name": "Times Now World"},
    {"id": "UCRK4FDIkUyslEAUdyRDdCtQ", "name": "News9 Live"},
    {"id": "UCJFOER35ggIWwsXh2ZDnqyg", "name": "The Economic Times"},
]

NATIONAL_HINDI_CHANNELS = [
    {"id": "UCt4t-jeY85JegMlZ-E5UWtA", "name": "Aaj Tak"},
    {"id": "UCx8Z14PpntdaxCt2hakbQLQ", "name": "The Lallantop"},
    {"id": "UCttspZesZIDEwwpVIgoZtWQ", "name": "India TV"},
    {"id": "UCRWFSbif-RFENbBrSiez1DA", "name": "ABP News"},
    {"id": "UCPP3etACgdUWvizcES1dJ8Q", "name": "News18 India"},
    {"id": "UC9CYT9gSNLevX5ey2_6CK0Q", "name": "NDTV India"},
    {"id": "UCOutOIcn_oho8pyVN3Ng-Pg", "name": "TV9 Bharatvarsh"},
    {"id": "UCMk9Tdc-d1BIcAFaSppiVkw", "name": "Times Now Navbharat"},
    {"id": "UC531MlZA5LUbeGwEN_zcppw", "name": "News18 Bihar Jharkhand"},
    {"id": "UC7wXt18f2iA3EDXeqAVuKng", "name": "Republic Bharat"},
    {"id": "UCIvaYmXn910QMdemBG3v1pQ", "name": "Zee News"},
    {"id": "UCKwucPzHZ7zCUIf7If-Wo1g", "name": "DD News"},
    {"id": "UC8eEZ-l5z_zzG8GT0Tu0PaA", "name": "India Dot Com"},
    {"id": "UCP_wvXToU5ohFLbTAkatvsw", "name": "Amar Ujala"},
    {"id": "UCCJRFl1Qjo83GG_09U-DIBA", "name": "Hindustan"},
    {"id": "UCvxi7_X1VSaMr_osIamYNaw", "name": "NMF News"},
    {"id": "UCOjgc1p2hJ4GZi6pQQoXWYQ", "name": "Oneindia Hindi"},
    {"id": "UCsNdeLwEZf86swPD3qJJ7Dw", "name": "News Nation"},
    {"id": "UCUGwnDFBHY52YhgVjn-Tvww", "name": "ABP Ganga"},
    {"id": "UCSKgOW8Pg_eZymYJyJc432g", "name": "Dainik Jagran"},
    {"id": "UCafYgzpyw7aIUYOLjjADu7w", "name": "News18 UP Uttarakhand"},
    {"id": "UCBwc2cbPpvxNCNEI2-8YrqQ", "name": "News18 MP Chhattisgarh"},
    {"id": "UCl8wUKzoUVzg7U6ky1ZR8hQ", "name": "Navbharat Times"},
    {"id": "UC_cZYFovNQTsKw1ZLmO_AMA", "name": "First India News"},
    {"id": "UClmlqOOktUTpfW0EkTiqSjQ", "name": "Aaj Tak HD"},
    {"id": "UCmphdqZNmqL72WJ2uyiNw5w", "name": "ABP Live"},
]

BENGALI_CHANNELS = [
    {"id": "UCv3rFzn-GHGtqzXiaq3sWNg", "name": "ABP Ananda"},
    {"id": "UCdF5Q5QVbYstYrTfpgUl0ZA", "name": "Zee 24 Ghanta"},
    {"id": "UCHCR4UFsGwd_VcDa0-a4haw",  "name": "TV9 Bangla"},
    {"id": "UCbf0XHULBkTfv2hBjaaDw9Q",  "name": "News18 Bangla"},
    {"id": "UCajVjEHDoVn_AHsunUZz_EQ",  "name": "Republic Bangla"},
    {"id": "UCdfOu3dJAYCc99mUy8hyfMw",  "name": "Aaj Tak Bangla"},
    {"id": "UCJ3I6MHOz5exARlTW_meOGQ",  "name": "Calcutta News"},
    {"id": "UC7GSS1hr39KcjdsKqAO76aQ",  "name": "Asianet News Bangla"},
    {"id": "UCHHYiu-zVZ307SN_gNqr88Q",  "name": "Tribe TV"},
    {"id": "UCe4GErYKwpMUJWZpxOiATYA",  "name": "DD Bangla News"},
    {"id": "UCycQauzU5n3DwQdgk3cw91A",  "name": "R Plus News 24x7"},
    {"id": "UC-drIvdQ0sZlyPXCizj4vgQ",  "name": "News Time Bangla"},
    {"id": "UC75RbtivNkL0XLElFAxg_zA",  "name": "High News"},
    {"id": "UCESY9RzEDPsb9lRLMxAirwQ",  "name": "Anandabazar Patrika"},
    {"id": "UCWoPoR2Jho2tbFV4TttLNdA",  "name": "Bartaman"},
    {"id": "UCPYZ_TMaFSsAGyedFpwyufA",  "name": "Ei Samay"},
    {"id": "UCkwTQGJelg1F-gV2ZmfPg8Q",  "name": "Aajkaal"},
    {"id": "UCLPCvTftdZpZQSM-mckfqXQ",  "name": "Sangbad Pratidin"},
    {"id": "UCdx_kjAFLinvdnEkdklgoNQ",  "name": "Ganashakti"},
    {"id": "UCXDw7ADM9CnoGPEk3aSsHaQ",  "name": "Uttar Banga Sambad"},
    {"id": "UCpthbAb5DDRfcG68VMn6q0g",  "name": "Indian Express Bangla"},
]

OPINION_CHANNELS = [
    {"id": "UCWWq6nFnUjje9RvGwYlIGTg", "name": "Arambagh TV"},
    {"id": "UCrp7axFgr0WTbFWybKFKZIQ", "name": "Campaigncalling Media"},
    {"id": "UC9YivGoN6UKWkl0k-8G1qyQ", "name": "Hothat Jodi Uthlo Kotha"},
    {"id": "UCEQSkASTH0bkG0AZ1kH8bhw", "name": "The News Bangla"},
    {"id": "UCefT7v-iDwAzbqQToY36mJw", "name": "Bongo TV"},
    {"id": "UCtODtHGNwmdSv7i5hekjrgA", "name": "Songe Adwitiya"},
    {"id": "UCvlgNfsMR3NfHYYLdikgUNA", "name": "Priyo Bandhu Media"},
    {"id": "UCqWuDZeimaWOI9TiDvZixAw", "name": "Madhyom"},
    {"id": "UCMi9LIv1yzHfGAIqnKZUfGA", "name": "Sanmoy Banerjee"},
    {"id": "UCkrE4tdQ4k8CLLOLAMQcftg", "name": "Jukti Tarko Songe Arka"},
    {"id": "UC6fbfKjLexg1nPf5NFK-QGQ", "name": "Shibam Das"},
    {"id": "UCgU5Ue1-bAtQb9xnK6q1zrA", "name": "Rudra Barta"},
    {"id": "UCRaZiQnlXlyxfwJYOyanC2w", "name": "India Hood"},
    {"id": "UC7KxtLAJdN9XvdOmbYj68Mg", "name": "Piglu 00"},
    {"id": "UCRqIKi1E-x69KBup7eyW0pQ", "name": "EVM News"},
    {"id": "UCd4Jgxg4VD-yTS30qAoMTCQ", "name": "Pinak Ki Bolche"},
    {"id": "UCKRhTf6EV4_E4vgRxah-CaA", "name": "Perfect Politics"},
    {"id": "UCSVHI858cXeEFUk8_G4tCKw", "name": "Political Daily"},
    {"id": "UC1FIRmUtxF6Yw4Y3CYjNBvw", "name": "SimpleASabc"},
    {"id": "UC9Ea502V2IJnBve8i7tdJ8w", "name": "Jagran Bangla"},
    {"id": "UCAjdUae-6-STu4AUY9VwBbw", "name": "News 16 Bharat"},
    {"id": "UCQFKW0TwxonvjVNz-vLjXWg", "name": "Speak U Bengal"},
    {"id": "UC_I5ulyzUKzgzqF46yR2WdA", "name": "The Digital Virus"},
    {"id": "UCTzlSKaQSIjrTTruodTJJMQ", "name": "CM News Media"},
    {"id": "UC2V1Hw_vCqWUbsUT_P-Xmpg", "name": "Nabanna Nimantran"},
    {"id": "UCxhf49woOiJeWiUzkBfuAEcQ", "name": "The Wall News"},
    {"id": "UCcsSoLkRobqNFfkS8TDg5qw", "name": "Sanmoy Speaks"},
    {"id": "UCdbT6v89UrmdKIob0tGUEXw", "name": "Bibidho News"},
    {"id": "UCPxBRy06Xut2pZ_Wgl528yg", "name": "Political Guru"},
    {"id": "UCVKZTEIghULaS-HFhjyWjlg", "name": "Banglasphere"},
]
